import Head from 'next/head'
import PrincipalView from '../components/DeskVersion/PrincipalView'
import Secondview from '../components/DeskVersion/SecondView'
import ThirdView from '../components/DeskVersion/ThirdView'


export default function Home() {
  return (
    <div >
      <Head>
        <title>SeaHorse Blue Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>


      
      <main>
        <PrincipalView />
        <Secondview />
        <ThirdView />
      </main>
    
      
    </div>
  )
}
